{"type": "error", "data": "Community Report Extraction Error", "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\community_reports\\community_reports_extractor.py\", line 58, in __call__\n    await self._llm(\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 104, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\tenacity\\__init__.py\", line 398, in <lambda>\n    self._add_action_func(lambda rs: rs.outcome.result())\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 48, in __call__\n    return await self._invoke_json(input, **kwargs)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 82, in _invoke_json\n    result = await generate()\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 74, in generate\n    await self._native_json(input, **{**kwargs, \"name\": call_name})\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 108, in _native_json\n    json_output = try_parse_json_object(raw_output)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\site-packages\\graphrag\\llm\\openai\\utils.py\", line 93, in try_parse_json_object\n    result = json.loads(input)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"C:\\Users\\10743215\\Documents\\RAG\\graphRAG\\graphragvenv\\lib\\json\\decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Unterminated string starting at: line 37 column 28 (char 7498)\n", "source": "Unterminated string starting at: line 37 column 28 (char 7498)", "details": null}
